### ISSUE TITLE
Is AMR WB supported?

### ISSUE THREAD

**Issue by Isaackingston** [kevinho/opencore-amr-android#10]
I need to support higher sample rate (16000) and in AMR NB(Narrow Band)the maximum sample rate is 8000. Would like to know whether is project is only for AMR NB or it has AMR WB(Wide Band) capability also?

**Comment by kevinho** [comment]
only nb supported，wb in progress

**Comment by kevinho** [comment]
if you need it now, maybe you should refer to the source code, and build yourself.
