### ISSUE TITLE
支持amr raw转pcm或者二进制数据么？

### ISSUE THREAD

**Issue by gucheng3116** [kevinho/opencore-amr-android#18]
你好，我最近在做安卓的语音识别功能。但是为了兼容ios，我这里只能用amr raw格式的。但是百度的语音识别接口要求用pcm格式的语音文件，或者amr wb格式的语音文件。请问下我要怎样将amr raw格式的转换成pcm或者wav格式呢？谢谢！

**Comment by kevinho** [comment]
https://github.com/kevinho/opencore-amr-android/blob/master/Codec/app/src/main/java/io/kvh/media/demo/AmrFileDecoder.java

**Comment by gucheng3116** [comment]
thank you
