### ISSUE TITLE
解码时加载so库报错

### ISSUE THREAD

**Issue by free01230** [kevinho/opencore-amr-android#2]
Trying to load lib /data/app-lib/。。。/libamr-codec.so 0x42c52660
Added shared lib /data/app-lib/。。。/libamr-codec.so 0x42c52660
No JNI_OnLoad found in /data/app-lib/。。。/libamr-codec.so 0x42c52660, skipping init
还是可以播放，不过是杂音，请问下这个是什么原因？

**Comment by kevinho** [comment]
请问你输入的amr的数据是怎么样的？
我目前主要是用来做encode。
加一下QQ群详细说吧，我希望能为你提供帮助
群号：453503476
