### ISSUE TITLE
Other architectures support

### ISSUE THREAD

**Issue by Potass** [kevinho/opencore-amr-android#5]
Hi,

as I can see, your library support only '**armeabi**' and '**armeabi-v7a**' architecture. Is it possible to add other architectures like '**x86**', '**x86_64**', '**mips**', '**mips64**' and '**arm64_v8a**' to support all android devices? Otherwise I cannot really use this library.

Thanks.

**Comment by kevinho** [comment]
Thanks for advice, i will try submit the missing prebuilds before this month ends, cos i am so busy these days..

**Comment by Potass** [comment]
Hi,

any update on this? Thanks.

**Comment by kevinho** [comment]
Hi,
I am building and testing the lib,
but i have no 64bit device, do you mind join my test?

**Comment by Potass** [comment]
Yes, you can release new version and I will test it next week.

**Comment by kevinho** [comment]
Hi,
I have uploaded the v1.1.0 version includes prebuilds for all archs, i have ran the test in Nexus 5, it works
Please help me to test it.

**Comment by kevinho** [comment]
Hi, any test results?

**Comment by Potass** [comment]
So far so good, but I also cannot test it on all architectures.. If any problem occurs I will let you know.

**Comment by kevinho** [comment]
Which devices do you have?
