### ISSUE TITLE
Decoder Cannot Process .amr 6 Byte Header

### ISSUE THREAD

**Issue by AAccount** [kevinho/opencore-amr-android#7]
First of all, thank you very much for making this library. I really appreciate it.

The AmrDecoder requires the 6 byte .amr file header of "23 21 41 4D 52 0A"  "#!amr." to be removed  when decoding .amr files. Otherwise the decoded pcm, sounds something like alien morse code. When you remove it, the decoded pcm sounds fine. Not difficult to manually in a hex editor or skip in an android app but maybe it would be nice to tell people about.

(The demo.amr included in the repository has the header in it so I was a bit confused why the demo sounded like alien morse code.)

**Comment by kevinho** [comment]
Thanks for reminding about this.
I assumed that people would know this knowledge when they decoding a amr file, so i didn't explain too much about it.
I have the readme file fix, please check out.
