### ISSUE TITLE
Any example for ArmFileEncoder?

### ISSUE THREAD

**Issue by Isaackingston** [kevinho/opencore-amr-android#9]
I could see there is a sample for ArmFileDecoder. Would be great if there is a sample for ArmFileEncoder as well so that it would be easy to use. Thanks in advance.

**Comment by kevinho** [comment]
you can refer this file https://github.com/kevinho/opencore-amr-android/blob/master/Codec/app/src/main/java/io/kvh/media/sound/Filer.java

**Comment by Isaackingston** [comment]
Understood that the sizes of these array are constants `short[] input = new short[160] ; byte[] out = new byte[32]` and these are limited to the maximum samplerate of AMR which is 8000.
